Patch coot.in: don't export PYTHONHOME (not perfect)
If PYTHONHOME=$COOT_PREFIX is exported, then python3.9 crashes with:
    Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
    Python runtime state: core initialized
    ModuleNotFoundError: No module named 'encodings'

This is because the python stdlib is _not_ in PYTHONHOME, as we have
installed python3.9 in a separate recipe,

When PYTHONHOME is exported, sys.path = [
  '/opt/homebrew/Cellar/coot/HEAD-8a55024/lib/python39.zip',
  '/opt/homebrew/Cellar/coot/HEAD-8a55024/lib/python3.9',
  '/opt/homebrew/Cellar/coot/HEAD-8a55024/lib/python3.9/lib-dynload',
]
None of those paths exists, so we can't find stdlib.

When it's unexported, sys.path = [
  '/opt/homebrew/Cellar/coot/HEAD-8a55024/libexec',
  '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',
  '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
  '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',
  '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages',
  '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/coot',
  '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/coot/rcrane',
  '/opt/homebrew/Cellar/coot/HEAD-8a55024/lib/python3.9/site-package',
].

Problems:
- Clearly, coot has installed itself into python3.9. Not ideal.
  I'd prefer it in a virtualenv which gets loaded with the
    /opt/homebrew/bin/coot loader executable (from coot.in).
  I think others were working on it?
- What's with the last path? It should be site-packages, not site-package.
  No idea where it's coming from.